/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "CS_1_aliases.h"
#include "CS_1.h"
#include "Pin_ISR_aliases.h"
#include "Pin_ISR.h"
#include "isr_ACC.h"
#include "UART_1.h"
#include "PWM_RG.h"
#include "PWM_B.h"
#include "PWM_Clock.h"
#include "RED_aliases.h"
#include "RED.h"
#include "GREEN_aliases.h"
#include "GREEN.h"
#include "BLU_aliases.h"
#include "BLU.h"
#include "MOSI_2_aliases.h"
#include "MOSI_2.h"
#include "SCKL_2_aliases.h"
#include "SCKL_2.h"
#include "CS_2_aliases.h"
#include "CS_2.h"
#include "MISO_2_aliases.h"
#include "MISO_2.h"
#include "SPIM_2.h"
#include "SPIM_2_PVT.h"
#include "SWITCH_IN_aliases.h"
#include "SWITCH_IN.h"
#include "Pin_Led_Blue_aliases.h"
#include "Pin_Led_Blue.h"
#include "Clock_debouncer.h"
#include "isr_DEBOUNCER.h"
#include "timer_clock.h"
#include "TIMER_button.h"
#include "isr_TIMER.h"
#include "timer_clock_1.h"
#include "Timer_Configuration.h"
#include "timer_clock_2.h"
#include "Timer_Blinking.h"
#include "isr_BLINKING.h"
#include "SPIM_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "SPIM_2_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

